#!name=一刻相册

#!desc=一刻相册会员解锁

#!homepage=https://github.com/chxm1023/Script_X

#!author=chxm1023

[Script]

# 百度网盘，一刻相册 解锁部分功能
一刻相册=type=http-response,pattern=^https?:\/\/pan\.baidu\.com\/(youai\/(user\/.+\/getminfo|membership\/.+\/adswitch)|(rest\/.+\/membership\/user|act\/.+\/(bchannel|welfare)\/list|api\/usercfg)),requires-body=1,max-size=0,script-path=https://ghproxy.com/https://raw.githubusercontent.com/chxm1023/Rewrite/main/bdcloud.js

[MITM]

hostname = %APPEND% pan.baidu.com